In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns',200)
pd.set_option('display.max_rows',200)

In [3]:
df=pd.read_csv("data/survey_results_public.csv")
schema_df=pd.read_csv("data/survey_results_schema.csv")

C:\Users\Sandeep\AppData\Local\Temp\ipykernel_5372\3857020513.py:1: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("data/survey_results_public.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49191 entries, 0 to 49190
Columns: 172 entries, ResponseId to JobSat
dtypes: float64(52), int64(1), object(119)
memory usage: 64.6+ MB

In [5]:
schema_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   qid       139 non-null    object
 1   qname     139 non-null    object
 2   question  139 non-null    object
 3   type      139 non-null    object
 4   sub       49 non-null     object
 5   sq_id     49 non-null     float64
dtypes: float64(1), object(5)
memory usage: 6.6+ KB

In [6]:
df.shape

(49191, 172)

In [7]:
schema_df.shape

(139, 6)

In [8]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [9]:
schema_df.columns

Index(['qid', 'qname', 'question', 'type', 'sub', 'sq_id'], dtype='object')

In [10]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
5,QID18,TechEndorse_6,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
6,QID18,TechEndorse_7,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
7,QID18,TechEndorse_8,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
8,QID18,TechEndorse_9,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
9,QID18,TechEndorse_13,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
10,QID18,TechEndorse_13_TEXT,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
11,QID19,TechOppose_1,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
12,QID19,TechOppose_2,What would turn you off or cause you to reject...,RO,Poor usability,2.0
13,QID19,TechOppose_3,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
14,QID19,TechOppose_5,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
15,QID19,TechOppose_7,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
16,QID19,TechOppose_9,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
17,QID19,TechOppose_11,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
18,QID19,TechOppose_13,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
19,QID19,TechOppose_16,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
20,QID19,TechOppose_15,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
21,QID19,TechOppose_15_TEXT,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
22,QID27,JobSatPoints_1,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
23,QID27,JobSatPoints_2,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
24,QID27,JobSatPoints_16,Rank the following attributes of your current ...,RO,You like your manager,3.0
25,QID27,JobSatPoints_3,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
26,QID27,JobSatPoints_4,Rank the following attributes of your current ...,RO,Expert mentors,5.0
27,QID27,JobSatPoints_5,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
28,QID27,JobSatPoints_6,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
29,QID27,JobSatPoints_7,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
30,QID27,JobSatPoints_8,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
31,QID27,JobSatPoints_9,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
32,QID27,JobSatPoints_10,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
33,QID27,JobSatPoints_11,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
34,QID27,JobSatPoints_13,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
35,QID27,JobSatPoints_14,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
36,QID27,JobSatPoints_15,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
37,QID27,JobSatPoints_15_TEXT,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
38,QID76,SO_Actions_1,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
39,QID76,SO_Actions_16,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
40,QID76,SO_Actions_3,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
41,QID76,SO_Actions_4,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
42,QID76,SO_Actions_5,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
43,QID76,SO_Actions_6,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
44,QID76,SO_Actions_9,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
45,QID76,SO_Actions_7,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
46,QID76,SO_Actions_10,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
47,QID76,SO_Actions_15,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
48,QID76,SO_Actions_15_TEXT,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
49,QID3,MainBranch,Are you someone who writes code? Please select...,MC,NaN,NaN
50,QID4,Age,What is your age?,MC,NaN,NaN
51,QID9,EdLevel,Which of the following best describes the high...,MC,NaN,NaN
52,QID7,Employment,Which of the following best describes your cur...,MC,NaN,NaN
53,QID8,EmploymentAddl,Which of the following <strong>additional</str...,MC,NaN,NaN
54,QID14,WorkExp,How many years of professional work experience...,TE,NaN,NaN
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new ...,MC,NaN,NaN
56,QID11,LearnCode,How did you learn to code in the past year? Se...,MC,NaN,NaN
57,QID12,LearnCodeAI,Did you spend time in the last year learning A...,MC,NaN,NaN
58,QID32,AILearnHow,How did you learn to code for AI in the past y...,MC,NaN,NaN
59,QID13,YearsCode,"Including any education, how many years have y...",TE,NaN,NaN
60,QID15,DevType,Which of the following describes your current ...,MC,NaN,NaN
61,QID16,OrgSize,Approximately how many people are employed by ...,MC,NaN,NaN
62,QID23,ICorPM,Are you an individual contributor or people ma...,MC,NaN,NaN
63,QID24,RemoteWork,Which best describes your current work situation?,MC,NaN,NaN
64,QID17,PurchaseInfluence,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
65,QID33,TechEndorseIntro,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
66,QID25,Industry,What industry do you work for in?,MC,NaN,NaN
67,QID26,JobSat,How satisfied are you in your current professi...,MC,NaN,NaN
68,QID28,AIThreat,Do you believe AI is a threat to your current ...,MC,NaN,NaN
69,QID29,NewRole,Have you considered a career change or transit...,MC,NaN,NaN
70,QID30,ToolCountWork,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
71,QID31,ToolCountPersonal,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
72,QID20,Country,Where do you live?,MC,NaN,NaN
73,QID21,Currency,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
74,QID22,CompTotal,What is your current total <b>annual</b> compe...,TE,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and m...",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,Was the programming language you use not liste...,TE,NaN,NaN
78,QID52,LanguagesWantEntry,Was the programming language you want to use n...,TE,NaN,NaN
79,QID45,DatabaseChoice,Did you work with database environments in the...,MC,NaN,NaN
80,QID35,Database,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
81,QID54,DatabaseHaveEntry,Was the database environment you use not liste...,TE,NaN,NaN
82,QID55,DatabaseWantEntry,Was the database environment you want to use n...,TE,NaN,NaN
83,QID46,PlatformChoice,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
84,QID36,Platform,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
85,QID56,PlatformHaveEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
86,QID57,PlatformWantEntry,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
87,QID47,WebframeChoice,Did you work with web frameworks and web techn...,MC,NaN,NaN
88,QID37,Webframe,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
89,QID58,WebframeHaveEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
90,QID59,WebframeWantEntry,Were the web frameworks and web technologies y...,TE,NaN,NaN
91,QID48,DevEnvsChoice,Did you work with development environments or ...,MC,NaN,NaN
92,QID38,DevEnvs,Which <strong>development environments and AI-...,Matrix,NaN,NaN
93,QID60,DevEnvHaveEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
94,QID61,DevEnvWantEntry,Was the developer environment or AI-enabled co...,TE,NaN,NaN
95,QID39,SOTags,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
96,QID62,SOTagsHaveEntry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
97,QID63,SOTagsWant Entry,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
98,QID40,OpSys,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
99,QID41,OfficeStackAsync,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
100,QID64,OfficeStackHaveEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
101,QID65,OfficeStackWantEntry,Was the collaborative work management and/or c...,TE,NaN,NaN
102,QID42,CommPlatform,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
103,QID66,CommPlatformHaveEntr,Was the community platform you use not listed ...,TE,NaN,NaN
104,QID67,CommPlatformWantEntr,Was the community platform you want to use not...,TE,NaN,NaN
105,QID50,AIModelsChoice,Did you utilize or integrate specific Large La...,MC,NaN,NaN
106,QID43,AIModels,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
107,QID68,AIModelsHaveEntry,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
108,QID69,AIModelsWantEntry,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
109,QID72,SOAccount,Do you have a Stack Overflow account?,MC,NaN,NaN
110,QID70,SOVisitFreq,How frequently would you say you visit Stack O...,MC,NaN,NaN
111,QID71,SODuration,How long have you used Stack Overflow?,MC,NaN,NaN
112,QID73,SOPartFreq,How frequently would you say you participate i...,MC,NaN,NaN
113,QID75,SO_Dev_Content,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
114,QID77,SOComm,Do you consider yourself a member of the Stack...,MC,NaN,NaN
115,QID97,SOFriction,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
116,QID78,AISelect,Do you currently use AI tools in your developm...,MC,NaN,NaN
117,QID79,AISent,How favorable is your stance on using AI tools...,MC,NaN,NaN
118,QID80,AIAcc,How much do you trust the accuracy of the outp...,MC,NaN,NaN
119,QID81,AIComplex,How well do the AI tools you use in your devel...,MC,NaN,NaN
120,QID82,AITool,Which parts of your development workflow are y...,Matrix,NaN,NaN
121,QID99,AIFrustration,"When using AI tools, which of the following pr...",MC,NaN,NaN
122,QID84,AIExplain,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
123,QID85,AIAgents,Are you using AI agents in your work (developm...,MC,NaN,NaN
124,QID83,AIAgentChange,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
125,QID86,AIAgent_Uses,What industry purposes or specific tasks are y...,MC,NaN,NaN
126,QID106,AgentUsesGeneral,,MC,NaN,NaN
127,QID87,AIAgentImpact,To what extent do you agree with the following...,Matrix,NaN,NaN
128,QID88,AIAgentChallenges,To what extent do you agree with the following...,Matrix,NaN,NaN
129,QID89,AIAgentKnowledge,You indicated you use or develop AI agents as ...,MC,NaN,NaN
130,QID107,AIAgentKnowWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
131,QID90,AIAgentOrchestration,You indicated you use or develop AI agents as ...,MC,NaN,NaN
132,QID102,AIAgentOrchWrite,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
133,QID91,AIAgentObserveSecure,You indicated you use or develop AI agents as ...,MC,NaN,NaN
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [15]:
df.loc[0]

ResponseId                                                                                  1
MainBranch                                                     I am a developer by profession
Age                                                                           25-34 years old
EdLevel                                       Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
Employment                                                                           Employed
EmploymentAddl                                Caring for dependents (children, elderly, etc.)
WorkExp                                                                                   8.0
LearnCodeChoose                             Yes, I am not new to coding but am learning ne...
LearnCode                                   Online Courses or Certification (includes all ...
LearnCodeAI                                 Yes, I learned how to use AI-enabled tools for...
AILearnHow                                                AI CodeGen tools or AI-enabled apps
YearsCode                                                                                14.0
DevType                                                                     Developer, mobile
OrgSize                                                                    20 to 99 employees
ICorPM                                                                         People manager
RemoteWork                                                                             Remote
PurchaseInfluence                           Yes, I influenced the purchase of a substantia...
TechEndorseIntro                                                                         Work
TechEndorse_1                                                                            10.0
TechEndorse_2                                                                             7.0
TechEndorse_3                                                                             9.0
TechEndorse_4                                                                             6.0
TechEndorse_5                                                                             3.0
TechEndorse_6                                                                            11.0
TechEndorse_7                                                                            12.0
TechEndorse_8                                                                             1.0
TechEndorse_9                                                                             8.0
TechEndorse_13                                                                           14.0
TechEndorse_13_TEXT                                                                       NaN
TechOppose_1                                                                             15.0
TechOppose_2                                                                              7.0
TechOppose_3                                                                              8.0
TechOppose_5                                                                             12.0
TechOppose_7                                                                             11.0
TechOppose_9                                                                              1.0
TechOppose_11                                                                             6.0
TechOppose_13                                                                            13.0
TechOppose_16                                                                             3.0
TechOppose_15                                                                            16.0
TechOppose_15_TEXT                                                                        NaN
Industry                                                                              Fintech
JobSatPoints_1                                                                            3.0
JobSatPoints_2                                                                            1.0
JobSatPoints_3                                                                            4.0
JobSatPoints_4                                                                            9.0
JobSatPoints_5                                                                            5.0
JobSatPoints_6                                                                           10.0
JobSatPoints_7                                                                           12.0
JobSatPoints_8                                                                           11.0
JobSatPoints_9                                                                            2.0
JobSatPoints_10                                                                           6.0
JobSatPoints_11                                                                           7.0
JobSatPoints_13                                                                          13.0
JobSatPoints_14                                                                          14.0
JobSatPoints_15                                                                          15.0
JobSatPoints_16                                                                           8.0
JobSatPoints_15_TEXT                                                                      NaN
AIThreat                                                                         I'm not sure
NewRole                                     I have neither consider or transitioned into a...
ToolCountWork                                                                             7.0
ToolCountPersonal                                                                         3.0
Country                                                                               Ukraine
Currency                                                                    EUR European Euro
CompTotal                                                                             52800.0
LanguageChoice                                                                            Yes
LanguageHaveWorkedWith                                       Bash/Shell (all shells);Dart;SQL
LanguageWantToWorkWith                                                                   Dart
LanguageAdmired                                                                          Dart
LanguagesHaveEntry                                                                        NaN
LanguagesWantEntry                                                                        NaN
DatabaseChoice                                                                            Yes
DatabaseHaveWorkedWith                                             Cloud Firestore;PostgreSQL
DatabaseWantToWorkWith                                                                    NaN
DatabaseAdmired                                                                           NaN
DatabaseHaveEntry                                                                         NaN
DatabaseWantEntry                                                                         NaN
PlatformChoice                                                                            Yes
PlatformHaveWorkedWith                      Amazon Web Services (AWS);Cloudflare;Firebase;...
PlatformWantToWorkWith                                                                    NaN
PlatformAdmired                                                                           NaN
PlatformHaveEntry                                                                         NaN
PlatformWantEntry                                                                         NaN
WebframeChoice                                                                             No
WebframeHaveWorkedWith                                                                    NaN
WebframeWantToWorkWith                                                                    NaN
WebframeAdmired                                                                           NaN
WebframeHaveEntry                                                                         NaN
WebframeWantEntry                                                                         NaN
DevEnvsChoice                                                                             Yes
DevEnvsHaveWorkedWith                       Android Studio;Notepad++;Visual Studio;Visual ...
DevEnvsWantToWorkWith                                                                     NaN
DevEnvsAdmired                                                                            NaN
DevEnvHaveEntry                                                                           NaN
DevEnvWantEntry                                                                           NaN
SOTagsHaveWorkedWith                                                                      NaN
SOTagsWantToWorkWith                                                                      NaN
SOTagsAdmired                                                                             NaN
SOTagsHaveEntry                                                                           NaN
SOTagsWant Entry                                                                          NaN
OpSysPersonal use                                                       Windows;MacOS;Android
OpSysProfessional use                                        Windows;MacOS;Android;iOS;iPadOS
OfficeStackAsyncHaveWorkedWith                    Confluence;GitHub;GitLab;Jira;Markdown File
OfficeStackAsyncWantToWorkWith                                                  Markdown File
OfficeStackAsyncAdmired                                                         Markdown File
OfficeStackHaveEntry                                                                      NaN
OfficeStackWantEntry                                                                      NaN
CommPlatformHaveWorkedWith                  Stack Overflow;Reddit;GitHub (public projects,...
CommPlatformWantToWorkWith                                                                NaN
CommPlatformAdmired                                                                       NaN
CommPlatformHaveEntr                                                                      NaN
CommPlatformWantEntr                                                                      NaN
AIModelsChoice                                                                            Yes
AIModelsHaveWorkedWith                      openAI GPT (chatbot models);openAI Image gener...
AIModelsWantToWorkWith                                                                    NaN
AIModelsAdmired                                                                           NaN
AIModelsHaveEntry                                                                         NaN
AIModelsWantEntry                                                                         NaN
SOAccount                                                                                 Yes
SOVisitFreq                                                              A few times per week
SODuration                                                             Between 5 and 10 years
SOPartFreq                                  I have never participated in Q&A on Stack Over...
SO_Dev_Content                                                                            NaN
SO_Actions_1                                                                              1.0
SO_Actions_16                                                                             NaN
SO_Actions_3                                                                              6.0
SO_Actions_4                                                                              2.0
SO_Actions_5                                                                              3.0
SO_Actions_6                                                                              7.0
SO_Actions_9                                                                              8.0
SO_Actions_7                                                                              9.0
SO_Actions_10                                                                            11.0
SO_Actions_15                                                                            15.0
SO_Actions_15_TEXT                                                                        NaN
SOComm                                                                                Neutral
SOFriction                                                               Rarely, almost never
AISelect                                          Yes, I use AI tools monthly or infrequently
AISent                                                                            Indifferent
AIAcc                                                              Neither trust nor distrust
AIComplex                                                       Bad at handling complex tasks
AIToolCurrently partially AI                Learning about a codebase;Writing code;Search ...
AIToolDon't plan to use AI for this task    Project planning;Deployment and monitoring;Lea...
AIToolPlan to partially use AI              Documenting code;Debugging or fixing code;Test...
AIToolPlan to mostly use AI                                                               NaN
AIToolCurrently mostly AI                                                                 NaN
AIFrustration                               AI solutions that are almost right, but not quite
AIExplain                                                                                  No
AIAgents                                    Yes, I use AI agents at work monthly or infreq...
AIAgentChange                                                         Not at all or minimally
AIAgent_Uses                                                             Software engineering
AgentUsesGeneral                                                                          NaN
AIAgentImpactSomewhat agree                 AI agents have increased my productivity.;AI a...
AIAgentImpactNeutral                        AI agents have helped me automate repetitive t...
AIAgentImpactSomewhat disagree                                                            NaN
AIAgentImpactStrongly agree                                                               NaN
AIAgentImpactStrongly disagree                                                            NaN
AIAgentChallengesNeutral                    I am concerned about the accuracy of the infor...
AIAgentChallengesSomewhat disagree          Integrating AI agents with my existing tools a...
AIAgentChallengesStrongly agree             The cost of using certain AI agent platforms i...
AIAgentChallengesSomewhat agree                                                           NaN
AIAgentChallengesStrongly disagree                                                        NaN
AIAgentKnowledge                                                                          NaN
AIAgentKnowWrite                                                                          NaN
AIAgentOrchestration                                                                Vertex AI
AIAgentOrchWrite                                                                          NaN
AIAgentObserveSecure                                                                      NaN
AIAgentObsWrite                                                                           NaN
AIAgentExternal                                                                       ChatGPT
AIAgentExtWrite                                                                           NaN
AIHuman                                                       When I don’t trust AI’s answers
AIOpen                                                  Troubleshooting, profiling, debugging
ConvertedCompYearly                                                                   61256.0
JobSat                                                                                   10.0
Name: 0, dtype: object

In [11]:
df.loc[0:2]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0

In [17]:
df.loc[[0,1,2],'Employment']

0                                             Employed
1                                             Employed
2    Independent contractor, freelancer, or self-em...
Name: Employment, dtype: object

In [14]:
df.loc[:,'Employment'] #df.Employment

0                                                 Employed
1                                                 Employed
2        Independent contractor, freelancer, or self-em...
3                                                 Employed
4        Independent contractor, freelancer, or self-em...
                               ...
49186                                             Employed
49187                                             Employed
49188                                             Employed
49189    Independent contractor, freelancer, or self-em...
49190                                              Student
Name: Employment, Length: 49191, dtype: object

In [15]:
df.loc[:,'Employment'].value_counts()

Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64

In [16]:
df.Employment.value_counts()

Employment
Employed                                                33750
Independent contractor, freelancer, or self-employed     6708
Student                                                  4428
Not employed                                             2227
Retired                                                   708
I prefer not to say                                       518
Name: count, dtype: int64

In [17]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'EdLevel', 'Employment',
       'EmploymentAddl', 'WorkExp', 'LearnCodeChoose', 'LearnCode',
       'LearnCodeAI',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='object', length=172)

In [18]:
df.loc[0:9,'ResponseId':'WorkExp']

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0
6,7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0
7,8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0
8,9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0
9,10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0