In [1]:
person = {"first":"Sravan Reddy","last":"Rokkam","email":"sravanreddy.rokkam@gmail.com"}

In [2]:
people = {"first":["Sravan Reddy"],"last":["Rokkam"],"email":["sravanreddy.rokkam@gmail.com"]}

In [3]:
person

{'first': 'Sravan Reddy',
 'last': 'Rokkam',
 'email': 'sravanreddy.rokkam@gmail.com'}

In [4]:
people

{'first': ['Sravan Reddy'],
 'last': ['Rokkam'],
 'email': ['sravanreddy.rokkam@gmail.com']}

In [5]:
people = {"first":["Sravan Reddy","Cruel","Suspect"],"last":["Rokkam","Goat","Glint"],"email":["sravanreddy.rokkam@gmail.com","cruelgoat@gmail.com","suspectglint@gmail.com"]}

In [6]:
people

{'first': ['Sravan Reddy', 'Cruel', 'Suspect'],
 'last': ['Rokkam', 'Goat', 'Glint'],
 'email': ['sravanreddy.rokkam@gmail.com',
  'cruelgoat@gmail.com',
  'suspectglint@gmail.com']}

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(people)

In [9]:
df

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [10]:
df.head()

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   3 non-null      object
 1   last    3 non-null      object
 2   email   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [12]:
df['email']

0    sravanreddy.rokkam@gmail.com
1             cruelgoat@gmail.com
2          suspectglint@gmail.com
Name: email, dtype: object

In [13]:
df.email

0    sravanreddy.rokkam@gmail.com
1             cruelgoat@gmail.com
2          suspectglint@gmail.com
Name: email, dtype: object

In [14]:
type(df.email)

pandas.core.series.Series

In [15]:
df[['first','last']]

          first    last
0  Sravan Reddy  Rokkam
1         Cruel    Goat
2       Suspect   Glint

In [16]:
type(df[['first','last']])

pandas.core.frame.DataFrame

In [17]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [18]:
df

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [24]:
df.iloc[0]

first                    Sravan Reddy
last                           Rokkam
email    sravanreddy.rokkam@gmail.com
Name: 0, dtype: object

In [25]:
type(df.iloc[0])

pandas.core.series.Series

In [26]:
df.iloc[[0,1]]

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com

In [27]:
type(df.iloc[[0,1]])

pandas.core.frame.DataFrame

In [30]:
#We can input the integer labels for iloc in any order and the rows will be fetched in the same order as of input.
df.iloc[[1,0,2]]

          first    last                         email
1         Cruel    Goat           cruelgoat@gmail.com
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [36]:
#Here we can use the second list to get the columns in same order mentioned in the columns list.
df.iloc[[0,1],[2,0]]

                          email         first
0  sravanreddy.rokkam@gmail.com  Sravan Reddy
1           cruelgoat@gmail.com         Cruel

In [37]:
df.loc[0]

first                    Sravan Reddy
last                           Rokkam
email    sravanreddy.rokkam@gmail.com
Name: 0, dtype: object

In [39]:
df.loc[[0,2,1]]

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
2       Suspect   Glint        suspectglint@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com

In [44]:
df.loc[[0,1,2]]

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [54]:
df.loc[[0,1,2],['last','email']]

     last                         email
0  Rokkam  sravanreddy.rokkam@gmail.com
1    Goat           cruelgoat@gmail.com
2   Glint        suspectglint@gmail.com

In [50]:
df.iloc[0,1]

'Rokkam'

In [17]:
type(df.iloc[0,1])

str

In [18]:
df.loc[2,'email']

'suspectglint@gmail.com'

In [19]:
type(df.loc[2,'email'])

str

In [20]:
df.loc[0:1,'first':'last']

          first    last
0  Sravan Reddy  Rokkam
1         Cruel    Goat

In [55]:
#Using slicing in pandas loc method but the last index in slice is inclusive and we need not put the slice in square braces.
df.loc[0:2,['last','email']]

     last                         email
0  Rokkam  sravanreddy.rokkam@gmail.com
1    Goat           cruelgoat@gmail.com
2   Glint        suspectglint@gmail.com

In [22]:
#And when we use slicing in iloc, the last indices are not inclusive unlike loc()
df.iloc[1:3,1:3]

    last                   email
1   Goat     cruelgoat@gmail.com
2  Glint  suspectglint@gmail.com

In [23]:
type(df.loc)

pandas.core.indexing._LocIndexer

In [24]:
type(df.iloc)

pandas.core.indexing._iLocIndexer