In [14]:
import pandas as pd

In [15]:
pd.set_option('display.max_rows',200)
pd.set_option('display.max_columns',200)

In [16]:
people = {"first":["Sravan Reddy","Cruel","Suspect"],"last":["Rokkam","Goat","Glint"],"email":["sravanreddy.rokkam@gmail.com","cruelgoat@gmail.com","suspectglint@gmail.com"]}

In [17]:
df = pd.DataFrame(people)

In [18]:
df

          first    last                         email
0  Sravan Reddy  Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel    Goat           cruelgoat@gmail.com
2       Suspect   Glint        suspectglint@gmail.com

In [19]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [20]:
#If we want to rename a specific column in the given dataframe, do that using df.rename() method.
df.rename(columns={'email':'email_address'},inplace=True)

In [21]:
#When we pass a list of string and assign to columns, the columns in the dataframe will be renamed.
df.columns = ['first name','last name','email']

In [22]:
df

     first name last name                         email
0  Sravan Reddy    Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel      Goat           cruelgoat@gmail.com
2       Suspect     Glint        suspectglint@gmail.com

In [23]:
#And if we want to apply some transformation(string changes) to column names, we can do it using functions of df.columns.str 
df.columns=df.columns.str.replace(' ','_')

In [24]:
df

     first_name last_name                         email
0  Sravan Reddy    Rokkam  sravanreddy.rokkam@gmail.com
1         Cruel      Goat           cruelgoat@gmail.com
2       Suspect     Glint        suspectglint@gmail.com

In [25]:
#Some of the other functions that are available in df.columns.str
dir(df.columns.str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 'partition',
 'removeprefix',
 'removesuffix',
 'repeat',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'slice',
 'slice_replace',
 'split',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'wrap',
 'zfill']

In [13]:
#Now let's understand how to update rows and columns in a given dataframe.

In [36]:
def transfrm(row):
    row['email']=row['email'].replace('gmail.com','hotmail.com')

In [37]:
df.apply(transfrm,axis=1)

0    None
1    None
2    None
dtype: object

In [44]:
#df.apply() - this function is used to transformtation to 
df['email'] = df['email'].apply(lambda x : x.lower())

In [40]:
df

     first_name last_name                           email
0  Sravan Reddy    Rokkam  SRAVANREDDY.ROKKAM@HOTMAIL.COM
1         Cruel      Goat           CRUELGOAT@HOTMAIL.COM
2       Suspect     Glint        SUSPECTGLINT@HOTMAIL.COM

In [41]:
#We can use both .at() and .loc() to update cells in a given dataframe.
#.loc is more versatile and can handle multiple rows and columns or even subsets of data.
df.loc[2,'email'] = 'sambaputra@gmail.com'

In [42]:
#We can use both .at() and .loc() to update cells in a given dataframe.
#Purpose: .at is optimized for accessing or setting a single scalar value in a DataFrame or Series.
df.at[1,'email'] = 'fragilegoat@gmail.com'

In [45]:
df

     first_name last_name                           email
0  Sravan Reddy    Rokkam  sravanreddy.rokkam@hotmail.com
1         Cruel      Goat           fragilegoat@gmail.com
2       Suspect     Glint            sambaputra@gmail.com

In [46]:
df['email']=df['email'].str.lower()

In [47]:
#apply() - this function is used to apply transformations at a series level in a dataframe.
df['email'].apply(len)

0    30
1    21
2    20
Name: email, dtype: int64

In [48]:
#applymap() - this function is used to apply transformations to all the cells in a dataframe.
df.applymap(len)

   first_name  last_name  email
0          12          6     30
1           5          4     21
2           7          5     20

In [49]:
df

     first_name last_name                           email
0  Sravan Reddy    Rokkam  sravanreddy.rokkam@hotmail.com
1         Cruel      Goat           fragilegoat@gmail.com
2       Suspect     Glint            sambaputra@gmail.com

In [50]:
#map() - function is used to replace/map values in a series as per the mapping shared in the input arguments.
#Now, let's try to change few of the firstnames in the dataframe
#And one thing to be noted here, it only changes the values that are mentioned in the dictionary argument. For the other values it just returned
#a NaN value(Not a Number). So to avoid such things, we can use replace() method.
df['first_name'].map({'Cruel':'Kind','Suspect':'Accept'})

0       NaN
1      Kind
2    Accept
Name: first_name, dtype: object

In [51]:
df

     first_name last_name                           email
0  Sravan Reddy    Rokkam  sravanreddy.rokkam@hotmail.com
1         Cruel      Goat           fragilegoat@gmail.com
2       Suspect     Glint            sambaputra@gmail.com

In [54]:
#replace() - function is used to replace values in a series as per the mapping shared in the input arguments.
#Now, let's try to change few of the firstnames in the dataframe
#And one thing to be noted here, it only changes the values that are mentioned in the dictionary argument.
df['first_name'].replace({'Cruel':'Kind','Suspect':'Accept'},inplace=True)

In [56]:
df['first_name']=df['first_name'].replace({'Cruel':'Kind','Suspect':'Accept'})

In [57]:
df

     first_name last_name                           email
0  Sravan Reddy    Rokkam  sravanreddy.rokkam@hotmail.com
1          Kind      Goat           fragilegoat@gmail.com
2        Accept     Glint            sambaputra@gmail.com