In [1]:
#In this notebook, we will look at various ways of sorting columns in pandas.

In [2]:
import pandas as pd

In [6]:
pokemon_data = {
    "Name": ["Pikachu", "Charmander", "Bulbasaur", "Squirtle", "Eevee"],
    "Type": ["Electric", "Fire", "Grass/Poison", "Water", "Normal"],
    "HP": [35, 39, 45, 44, 55],
    "Attack": [55, 52, 49, 48, 55],
    "Defense": [40, 43, 49, 65, 50]
}

In [7]:
df =pd.DataFrame(pokemon_data)

In [8]:
df

         Name          Type  HP  Attack  Defense
0     Pikachu      Electric  35      55       40
1  Charmander          Fire  39      52       43
2   Bulbasaur  Grass/Poison  45      49       49
3    Squirtle         Water  44      48       65
4       Eevee        Normal  55      55       50

In [9]:
df.sort_index(ascending=False)

         Name          Type  HP  Attack  Defense
4       Eevee        Normal  55      55       50
3    Squirtle         Water  44      48       65
2   Bulbasaur  Grass/Poison  45      49       49
1  Charmander          Fire  39      52       43
0     Pikachu      Electric  35      55       40

In [10]:
df

         Name          Type  HP  Attack  Defense
0     Pikachu      Electric  35      55       40
1  Charmander          Fire  39      52       43
2   Bulbasaur  Grass/Poison  45      49       49
3    Squirtle         Water  44      48       65
4       Eevee        Normal  55      55       50

In [11]:
df.sort_values(by='Name')

         Name          Type  HP  Attack  Defense
2   Bulbasaur  Grass/Poison  45      49       49
1  Charmander          Fire  39      52       43
4       Eevee        Normal  55      55       50
0     Pikachu      Electric  35      55       40
3    Squirtle         Water  44      48       65

In [21]:
#Here in pandas, we use .sort_values() method to sort a given dataframe based on the columns shared in the list 
#and also we can use this sort a single series of values. 
#by - to specify the column(s) on which data needs to be sorted.
#ascending - to specify the order of data sort ascending/descending for the corresponding column.
df.sort_values(by=['Attack','Name'],ascending=[False,True],inplace=True)

In [15]:
df

         Name          Type  HP  Attack  Defense
4       Eevee        Normal  55      55       50
0     Pikachu      Electric  35      55       40
1  Charmander          Fire  39      52       43
2   Bulbasaur  Grass/Poison  45      49       49
3    Squirtle         Water  44      48       65

In [24]:
#This we have seen earlier in index file. This method can be used to sort the given dataframe by index.
df.sort_index(inplace=True)

In [25]:
df

         Name          Type  HP  Attack  Defense
0     Pikachu      Electric  35      55       40
1  Charmander          Fire  39      52       43
2   Bulbasaur  Grass/Poison  45      49       49
3    Squirtle         Water  44      48       65
4       Eevee        Normal  55      55       50

In [27]:
#This is the scenario where we are trying to sort a single series of data.
df['Name'].sort_values(ascending=False)

3      Squirtle
0       Pikachu
4         Eevee
1    Charmander
2     Bulbasaur
Name: Name, dtype: object

In [28]:
df

         Name          Type  HP  Attack  Defense
0     Pikachu      Electric  35      55       40
1  Charmander          Fire  39      52       43
2   Bulbasaur  Grass/Poison  45      49       49
3    Squirtle         Water  44      48       65
4       Eevee        Normal  55      55       50